// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ScrapperWebApp.Models;

public partial class Atividade
{
    public string DsAtividade { get; set; }
    public int NoAtividade { get; set; }
}