// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace ScrapperWebApp.Models;

public partial class Cep
{
    public string CdLogradouro { get; set; }

    public string CdBairro { get; set; }

    public string CdMunicipio { get; set; }

    public string CdEstado { get; set; }

    public string NoCep { get; set; }
}