// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ScrapperWebApp.Models;

public partial class EmpAtividade
{
    public int NoAtividade { get; set; }

    public string CdAtvPrincipal { get; set; }

    public long? NoCnpj { get; set; }

    public virtual Empresa NoCnpjNavigation { get; set; }
}