// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.EntityFrameworkCore;
using ScrapperWebApp.Data;
using System.ComponentModel.DataAnnotations.Schema;

namespace ScrapperWebApp.Models;

public partial class ScrapperDbContext : DbContext
{
    public ScrapperDbContext(DbContextOptions<ScrapperDbContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Atividade> Atividades { get; set; }

    public virtual DbSet<Cep> Ceps { get; set; }

    public virtual DbSet<EmpAtividade> EmpAtividades { get; set; }

    public virtual DbSet<Empresa> Empresas { get; set; }

    public virtual DbSet<Filtro> Filtros { get; set; }
    public virtual DbSet<NatJur> NatJurs { get; set; }

    public virtual DbSet<Socio> Socios { get; set; }
    public virtual DbSet<Telefone> Telefones { get; set; }
    public virtual DbSet<UraError> UraErrors { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        //optionsBuilder.EnableSensitiveDataLogging();
    }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Atividade>(entity =>
        {
            entity.HasKey(e => e.NoAtividade).HasName("PK__Atividad__00E6730B9DBBF287");

            entity.ToTable("Atividade");

            entity.Property(e => e.NoAtividade)
                .ValueGeneratedNever()
                .HasColumnName("no_atividade");
            entity.Property(e => e.DsAtividade)
                .HasMaxLength(255)
                .IsUnicode(false)
                .HasColumnName("ds_atividade");
        });

        modelBuilder.Entity<Cep>(entity =>
        {
            entity.HasKey(e => new { e.NoCep, e.CdMunicipio }).HasName("PK__Cep__0078B694D03858C7");

            entity.ToTable("Cep");

            entity.Property(e => e.NoCep)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("no_cep");
            entity.Property(e => e.CdMunicipio)
                .HasMaxLength(255)
                .IsUnicode(false)
                .HasColumnName("cd_municipio");
            entity.Property(e => e.CdBairro)
                .HasMaxLength(255)
                .IsUnicode(false)
                .HasColumnName("cd_bairro");
            entity.Property(e => e.CdEstado)
                .HasMaxLength(255)
                .IsUnicode(false)
                .HasColumnName("cd_estado");
            entity.Property(e => e.CdLogradouro)
                .HasMaxLength(255)
                .IsUnicode(false)
                .HasColumnName("cd_logradouro");
        });

        modelBuilder.Entity<EmpAtividade>(entity =>
        {
            entity.HasKey(e => new { e.NoAtividade, e.NoCnpj }).HasName("PK__Emp_Ativ__5B112571AE53D8E7");

            entity.ToTable("Emp_Atividade");

            entity.Property(e => e.NoAtividade).HasColumnName("no_atividade");
            entity.Property(e => e.NoCnpj).HasColumnName("no_cnpj");
            entity.Property(e => e.CdAtvPrincipal)
                .HasMaxLength(255)
                .IsUnicode(false)
                .HasColumnName("cd_atv_principal");

            entity.HasOne(d => d.NoCnpjNavigation).WithMany(p => p.EmpAtividades)
                .HasForeignKey(d => d.NoCnpj)
                .OnDelete(DeleteBehavior.ClientCascade)
                .HasConstraintName("FK__Emp_Ativi__no_cn__65370702");
        });

        modelBuilder.Entity<Empresa>(entity =>
        {
            entity.HasKey(e => e.NoCnpj).HasName("PK__Empresa__BF7567A43A69EBC2");

            entity.ToTable("Empresa");

            entity.Property(e => e.NoCnpj)
                .ValueGeneratedNever()
                .HasColumnName("no_cnpj");
            entity.Property(e => e.CdEmail)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("cd_email");
            entity.Property(e => e.CdFantasia)
                .HasMaxLength(255)
                .IsUnicode(false)
                .HasColumnName("cd_fantasia");
            entity.Property(e => e.CdLogra)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("cd_logra");
            entity.Property(e => e.CdMei)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("cd_mei");
            entity.Property(e => e.CdNumero)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("cd_numero");
            entity.Property(e => e.CdRzsocial)
                .HasMaxLength(255)
                .IsUnicode(false)
                .HasColumnName("cd_rzsocial");
            entity.Property(e => e.CdSituacao)
                .HasMaxLength(255)
                .IsUnicode(false)
                .HasColumnName("cd_situacao");
            entity.Property(e => e.CdTipo)
                .HasMaxLength(255)
                .IsUnicode(false)
                .HasColumnName("cd_tipo");
            entity.Property(e => e.DtAbertura)
                .HasColumnType("date")
                .HasColumnName("dt_abertura");
            entity.Property(e => e.DtSituacao)
                .HasColumnType("date")
                .HasColumnName("dt_situacao");
            entity.Property(e => e.NoCep)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("no_cep");
            entity.Property(e => e.NoFone)
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("no_fone");
            entity.Property(e => e.NoNatjur).HasColumnName("no_natjur");
            entity.Property(e => e.VlCapsocial).HasColumnName("vl_capsocial");

            entity.HasOne(d => d.NoNatjurNavigation).WithMany(p => p.Empresas)
                .HasForeignKey(d => d.NoNatjur)
                .HasConstraintName("FK_Emp_Natjur");
        });

        modelBuilder.Entity<Filtro>(entity =>
        {
            entity.HasKey(e => new { e.NoCep, e.DtInicial, e.DtFinal }).HasName("PK__Filtro__94B19BA4EBBC1B16");

            entity.ToTable("Filtro");

            entity.Property(e => e.NoCep)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("no_cep");
            entity.Property(e => e.DtInicial)
                .HasColumnType("date")
                .HasColumnName("dt_inicial");
            entity.Property(e => e.DtFinal)
                .HasColumnType("date")
                .HasColumnName("dt_final");
            entity.Property(e => e.CdMei)
                .HasMaxLength(5)
                .IsUnicode(false)
                .HasColumnName("cd_mei");
            entity.Property(e => e.DtExecucao)
                .HasColumnType("date")
                .HasColumnName("dt_execucao");
            entity.Property(e => e.NoContador).HasColumnName("no_contador");
        });

        modelBuilder.Entity<NatJur>(entity =>
        {
            entity.HasKey(e => e.NoNatjur).HasName("PK__Nat_Jur__21708B5C8654ECDD");

            entity.ToTable("Nat_Jur");

            entity.Property(e => e.NoNatjur)
                .ValueGeneratedNever()
                .HasColumnName("no_natjur");
            entity.Property(e => e.DsNatjur)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("ds_natjur");
        });

        modelBuilder.Entity<Socio>(entity =>
        {
            entity.HasKey(e => new { e.DsSocio, e.DsTpSocio, e.NoCnpj }).HasName("PK__Socios__7D54B1BCFDE4D09B");

            entity.Property(e => e.DsSocio)
                .HasMaxLength(255)
                .IsUnicode(false)
                .HasColumnName("ds_socio");
            entity.Property(e => e.DsTpSocio)
                .HasMaxLength(255)
                .IsUnicode(false)
                .HasColumnName("ds_tp_socio");
            entity.Property(e => e.NoCnpj).HasColumnName("no_cnpj");

            entity.HasOne(d => d.NoCnpjNavigation).WithMany(p => p.Socios)
                .HasForeignKey(d => d.NoCnpj)
                .OnDelete(DeleteBehavior.ClientCascade)
                .HasConstraintName("FK__Socios__no_cnpj__489AC854");
        });

        modelBuilder.Entity<Telefone>(entity =>
        {
            entity.HasKey(e => new { e.NoFone, e.NoCnpj }).HasName("PK__Telefone__9DED88EAD6FCD351");

            entity.ToTable("Telefone");

            entity.Property(e => e.NoFone)
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("no_fone");
            entity.Property(e => e.NoCnpj).HasColumnName("no_cnpj");

            entity.HasOne(d => d.NoCnpjNavigation).WithMany(p => p.Telefones)
                .HasForeignKey(d => d.NoCnpj)
                .OnDelete(DeleteBehavior.ClientCascade)
                .HasConstraintName("FK__Telefone__no_cnp__625A9A57");
        });

        modelBuilder.Entity<UraError>(entity =>
        {
            entity.HasKey(e => e.NoUraErr).HasName("PK__Ura_Erro__629DCF3BDD301CE8");

            entity.ToTable("Ura_Errors");

            entity.Property(e => e.NoUraErr).HasColumnName("no_ura_err");
            entity.Property(e => e.CdEmail)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("cd_email");
            entity.Property(e => e.CdErrors)
                .HasMaxLength(1000)
                .IsUnicode(false)
                .HasColumnName("cd_errors");
            entity.Property(e => e.CdRzsocial)
                .HasMaxLength(150)
                .IsUnicode(false)
                .HasColumnName("cd_rzsocial");
            entity.Property(e => e.DsSocio)
                .HasMaxLength(150)
                .IsUnicode(false)
                .HasColumnName("ds_socio");
            entity.Property(e => e.NoCnpj).HasColumnName("no_cnpj");
            entity.Property(e => e.NoFone1)
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("no_fone1");
            entity.Property(e => e.NoFone2)
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("no_fone2");
            entity.Property(e => e.NoFone3)
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("no_fone3");
            entity.Property(e => e.NoFone4)
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("no_fone4");

            entity.HasOne(d => d.NoCnpjNavigation).WithMany(p => p.UraErrors)
                .HasForeignKey(d => d.NoCnpj)
                .HasConstraintName("FK__Ura_Error__no_cn__1E6F845E");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}