// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ScrapperWebApp.Models;

public partial class Socio
{
    public string DsSocio { get; set; }

    public string DsTpSocio { get; set; }

    public long NoCnpj { get; set; }

    public virtual Empresa NoCnpjNavigation { get; set; }
}