// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable

namespace ScrapperWebApp.Models;

public partial class Telefone
{
    public string NoFone { get; set; }

    public long NoCnpj { get; set; }

    public virtual Empresa NoCnpjNavigation { get; set; }
}